PS D:\FaceGuardNotify> python app.py
C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask_limiter\extension.py:364: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.14.198:5000
Press CTRL+C to quit
127.0.0.1 - - [29/Sep/2025 00:14:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Sep/2025 00:14:16] "GET /static/css/style.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Sep/2025 00:14:16] "GET /static/js/app.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Sep/2025 00:14:24] "GET /api/results HTTP/1.1" 404 -
127.0.0.1 - - [29/Sep/2025 00:14:34] "POST /login HTTP/1.1" 200 -
[2025-09-29 00:14:34,963] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\FaceGuardNotify\blueprints\auth\routes.py", line 85, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\FaceGuardNotify\blueprints\admin\routes.py", line 16, in dashboard
    total_voters = Voter.query.count()
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\query.py", line 3146, in count
    self._legacy_from_self(col).enable_eagerloads(False).scalar()
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\query.py", line 2835, in scalar
    ret = self.one()
          ^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\query.py", line 2808, in one
    return self._iter().one()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\sqlalchemy\orm\session.py", line 2239, in _execute_internal
    bind = self.get_bind(**bind_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask_sqlalchemy\session.py", line 53, in get_bind
    engines = self._db.engines
              ^^^^^^^^^^^^^^^^
  File "C:\Users\mithr\AppData\Roaming\Python\Python311\site-packages\flask_sqlalchemy\extension.py", line 690, in engines
    raise RuntimeError(
RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
127.0.0.1 - - [29/Sep/2025 00:14:34] "GET /admin/dashboard HTTP/1.1" 500 -
127.0.0.1 - - [29/Sep/2025 00:15:23] "GET /api/results HTTP/1.1" 404 -
